language: python

python:
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
  - "pip install coverage"
  - "pip install ."

script:
  - "python -m unittest discover -s ./tests -t ./tests"
  - "coverage run --source ./ setup.py test"

after_success:
  - "codecov"